### ISSUE TITLE
Feature request: Also upload movie clips

### ISSUE THREAD

**Issue by d5ve** [stephanepechard/photobackup-clients#1]
Hi Stéphane,

I've just started using the PhotoBackup Android app and love it - thanks for working on this. Are there any plans to, optionally, upload movie clips as well? The file sizes would be far larger, so this may not work for some people, but I'd like to make full use of my mobile data plan per month!

As an aside, I've just released a perl server implementation to [CPAN](https://metacpan.org/pod/Net::PhotoBackup::Server) It's also on [github](https://github.com/d5ve/p5-Net-PhotoBackup-Server) I've been using it with the Android app for a few days now, and it seems to work well.

Cheers,

Dave

**Comment by stephanepechard** [comment]
It's on my TODO list, but it is not that easy. Videos are commonly bigger than pictures, therefore need fancy upload with resume handling, both on client and server sides.

I'll check your Perl version, and come back to you about it.
